### PR TITLE
Fixes #118: On multisite-convert, don't assume site_id is 1

### LINKED ISSUE #118: multisite-convert causing incorrect site_id
- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bg reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

When running `wp core multisite-convert` on a fresh single site installation, the `site_id` is set to 4. This appears in the database (`wp_blogs.site_id`, `wp_sitemeta.site_id`, etc). However, the `SITE_ID_CURRENT_SITE` constant in `wp-config.php` is still 1.

**Describe how other contributors can replicate this bug**

I do not know that this can be replicated; it does not happen in my local installation. What I'm hoping for are some suggestions on how to debug this. Here are some aspects of the installation that could maybe be relevant:
- Using a Galera database cluster accessed through maxscale (db proxy/load balancer)
- Server is an HA cluster of two nodes. Command is being run on only one node, however.
- PHP-FPM

Here are the exact steps I took:
1. Deploy WordPress core code to server.
2. Begin installation through the web interface.
3. Copy wp-config code to wp-config.php
4. Finish installation (by clicking "Run installation")
5. Run `wp core multisite-convert`

When I add an echo for debugging around line 636 of src/Core_Command.php, I see that `$assoc_args['site_id']` is 1. This variable is used a few lines later like so:
```
$result = populate_network(
    $assoc_args['site_id'],
    $domain,
    get_option( 'admin_email' ),
    $assoc_args['title'],
    $assoc_args['base'],
    $assoc_args['subdomains']
);
```

**Describe what you would expect as the correct outcome**

The site_id being set to 1, per the default.

**Let us know what environment you are running this on**

```
OS:     Linux 3.10.0-957.5.1.el7.x86_64 #1 SMP Wed Dec 19 10:46:58 EST 2018 x86_64
Shell:  /bin/bash
PHP binary:     /opt/remi/php71/root/usr/bin/php
PHP version:    7.1.25
php.ini used:   /etc/opt/remi/php71/php.ini
WP-CLI root dir:        phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:      phar://wp-cli.phar/vendor
WP_CLI phar path:       /var/www/sphinx/releases/20190423202456/public
WP-CLI packages dir:    /usr/local/src/wp-cli-packages/current/
WP-CLI global config:   /usr/local/src/wp-cli-packages/current/wp-cli.yml
WP-CLI project config:
WP-CLI version: 2.1.0
```

### PR DESCRIPTION
**Pull request by azito122**
In the `populate_network` function, which is used by `core multisite-convert`, I observe the following code (line 1007 of `wp-admin/includes/schema.php` at v4.9.9):

```
if ( 1 == $network_id ) {
	$wpdb->insert( $wpdb->site, array( 'domain' => $domain, 'path' => $path ) );
	$network_id = $wpdb->insert_id;
} else {
	$wpdb->insert( $wpdb->site, array( 'domain' => $domain, 'path' => $path, 'id' => $network_id ) );
}
```

My understanding of the code in `Core_Command.php` is that `multisite-convert` is invoking `populate_network()`, and passing `1` as the site id (`$network_id`). As you can see, the WP core code then sets the network_id equal to the result of the INSERT query against wp_site. In most cases, this would be 1; however, if one has configured auto_increment_increment -- as is standard practice for database clusters -- then the `wp_site` table will store the site as id 4, and the code will generate the rest of the data using that same id.

From the perspective of `core-command`, this is mostly not a concern. However, it does appear that the constant `SITE_ID_CURRENT_SITE` is hardcoded with value 1. This produces an inconsistency between the config file and the database which is less than ideal. The solution is simple -- store the actual site_id/network_id and use that instead of a hardcoded 1. The only downside is that it means one extra database query (functions like `get_main_network_id()` appear to be accessing some kind of cache, or perhaps are falling back to default, and only return 1).

### CODE REVIEW

File: src/Core_Command.php [hunk 1]
```diff
@@ -642,6 +642,9 @@ private function _multisite_convert( $assoc_args ) {
 			$assoc_args['subdomains']
 		);
 
+		// Fetch what the actual site id turned out to be.
+		$site_id = get_current_site()->id;
```
Comment (schlessera) [inline src/Core_Command.php]: The multisite-specific code has not been loaded at this point, so the function `get_current_site()` does not exist.

See test failures here: https://travis-ci.org/wp-cli/core-command/jobs/524578309#L668

You might be able to directly reference the `$current_site` global, but you'll have to check first whether that is populated.

File: src/Core_Command.php [hunk 2]
```diff
@@ -673,7 +676,7 @@ private function _multisite_convert( $assoc_args ) {
 \$base = '{$assoc_args['base']}';
 define( 'DOMAIN_CURRENT_SITE', '{$domain}' );
 define( 'PATH_CURRENT_SITE', '{$assoc_args['base']}' );
-define( 'SITE_ID_CURRENT_SITE', 1 );
+define( 'SITE_ID_CURRENT_SITE', $site_id );
```
Comment (schlessera) [inline src/Core_Command.php]: CS: Use curly braces around variable substitution
```suggestion
define( 'SITE_ID_CURRENT_SITE', {$site_id} );
```

**Comment by azito122** [comment]
I made two changes to the code:

1. Use a direct DB call to get the site id. This should have been in my original pull request, but I missed committing the final changes I had made locally. I found that none of the multisite functions succeeded in obtaining the actual site id. Incidentally, this also fixes your first change request.

2. Escaped the string as you suggested.

File: src/Core_Command.php (hunk 1 above)
Comment (azito122) [reply src/Core_Command.php]: This is resolved in the latest code. I found that it was necessary to use a direct DB query instead, in order to get the correct site id.

File: src/Core_Command.php [hunk 3]
```diff
@@ -642,6 +642,8 @@ private function _multisite_convert( $assoc_args ) {
 			$assoc_args['subdomains']
 		);
 
+		$site_id = $wpdb->get_var("SELECT id FROM $wpdb->site");
```
Comment (schlessera) [inline src/Core_Command.php]: This can use some fool-proofing (you can never be sure with WordPress...).
```suggestion
		$site_id = $wpdb->get_var( "SELECT id FROM $wpdb->site" );
		$site_id = ( null === $site_id ) ? 1 : (int) $site_id;
```

File: src/Core_Command.php [hunk 4]
```diff
@@ -673,7 +675,7 @@ private function _multisite_convert( $assoc_args ) {
 \$base = '{$assoc_args['base']}';
 define( 'DOMAIN_CURRENT_SITE', '{$domain}' );
 define( 'PATH_CURRENT_SITE', '{$assoc_args['base']}' );
-define( 'SITE_ID_CURRENT_SITE', 1 );
+define( 'SITE_ID_CURRENT_SITE', '{$site_id}' );
```
Comment (schlessera) [inline src/Core_Command.php]:
```suggestion
define( 'SITE_ID_CURRENT_SITE', $site_id );
```

**Comment by schlessera** [comment]
@azito122 Are you still interested in working on this?

**Comment by schlessera** [comment]
Thanks for the PR, @azito122 !
