### PR TITLE
Sanitize database at the end of install to prevent duplicate data

### LINKED ISSUE #75: multisite-install generates two site_admins meta on starter site
This is as of commit 0e825668 of this repo.

I have a global `wp-cli.yml` where I have admin user details saved. Also `wpd` is aliased to the dev version of wp-cli.

To reproduce the issue:

```
$ which wpd
wpd: aliased to ~/wp-cli/bin/wp
$ mkdir wpcli-multisite && cd wpcli-multisite && wpd core download
Downloading WordPress 4.9.7 (en_US)...
md5 hash verified: 50efc5822bf550e9a526b9b9f4469b0d
Success: WordPress downloaded.
$ wpd core config --dbname="wpclims"
Success: Generated 'wp-config.php' file.
$ wpd db create
Success: Database created.
$ wpd core multisite-install --url="https://wpcms.test" --title="WPCLI Hack"
Created single site database tables.
Set up multisite database tables.
Success: Network installed. Don't forget to set up rewrite rules (and a .htaccess file, if using Apache).
```

Then opening the database, I see the following:

screen shot 2018-07-20 at 07 29 19

## Why is this a problem?

When using persistent cache (redis), the value of `site_admins` is empty, and I lose access to the Network Admin dashboard.

If persistent cache is not used, then `wp_load_core_site_options` loads all important site meta into memory, and caches them one by one in a global. Because `site_admins` is present twice, the second one overwrites the first, and because the second one is the valid value, it accidentally works.

If persistent cache IS used, `wp_load_core_site_options` doesn't do anything, and a call to `get_super_admins` ends up at `get_network_option`, which retrieves the option the first time it's needed with 

```
$row = $wpdb->get_row( $wpdb->prepare( "SELECT meta_value FROM $wpdb->sitemeta WHERE meta_key = %s AND site_id = %d", $option, $network_id ) );
```

That one grabs the first row, which is empty, thereby breaking functionality.

### PR DESCRIPTION
**Pull request by javorszky**
Closes #75 

If the multisite constants are already in `wp-config.php`, there's no way to stop `populate_network` to add an empty `site_admins` option when creating a new install.

This PR adds code that, at the end, would remove all empty `site_admins` options. Later `multisite-install` calls `add_site_admins` which checks whether a user is a super admin, which would fail because the option exists, but is empty, so it would add another entry to the sitemeta table.

So normally the `add_site_admins` would just update the site_admins, and that should work. Not in this case.

`update_network_option` will check the existing value of the option, and if it's `false`, then it will use `add_network_option` [because `false` means the option doesn't exist in the database](https://github.com/WordPress/WordPress/blob/master/wp-includes/option.php#L1565-L1590).

`get_network_option` will return whatever is stored in the cache. If that happens to be nothing, then the first time a query is ran, it will check in the database, and if it's not in the database, [it will store it in a `$notoptions` array, and store that in the cache](https://github.com/WordPress/WordPress/blob/master/wp-includes/option.php#L1275-L1290).

The first time `site_admins` is queried, the database is practically empty, so the `site_admins` key ends up being part of the `$notoptions` variable and cache.

Subsequent query to `get_network_option` will [hit the part where it's a `notoption` and return the default value - which is `false`](https://github.com/WordPress/WordPress/blob/master/wp-includes/option.php#L1248-L1267).

Which means in order to get this working, we need to actually delete the empty `site_admins` option, because a new one will be added anyways.

### CODE REVIEW

File: src/Core_Command.php [hunk 1]
```diff
@@ -681,6 +685,22 @@ private function _multisite_convert( $assoc_args ) {
 			} else {
 				WP_CLI::warning( "Multisite constants could not be written to 'wp-config.php'. You may need to add them manually:" . PHP_EOL . $ms_config );
 			}
+		} else {
+			/**
```
Comment (schlessera) [inline src/Core_Command.php]: This is not a valid docblock, as it is not attached to an entity that can receive docblocks. Please use a regular multiline comment instead.

File: src/Core_Command.php [hunk 2]
```diff
@@ -681,6 +685,22 @@ private function _multisite_convert( $assoc_args ) {
...
+			 * Multisite constants are defined, therefore we already have an empty site_admins site meta
```
Comment (schlessera) [inline src/Core_Command.php]: CS: Terminate first comment line with a period.

File: src/Core_Command.php [hunk 3]
```diff
@@ -681,6 +685,22 @@ private function _multisite_convert( $assoc_args ) {
...
+			 *
+			 * Code based on parts of delete_network_option
+			 */
+			$rows = $wpdb->get_results( "SELECT meta_id, site_id FROM {$wpdb->sitemeta} WHERE meta_key = 'site_admins'" );
```
Comment (schlessera) [inline src/Core_Command.php]: I'd prefer this to only delete site admin options that are empty (by just adding that as an additional WHERE clause). Otherwise, someone might already have imported a pre-existing DB that contained the proper admin settings, and we are then deleting everything.

**Comment by schlessera** [comment]
@javorszky Thanks for the PR, the code looks good to me.

Would you be up to writing a Behat regression test for that?

**Comment by javorszky** [comment]
I can try. Not sure how I could test having object caching in place though.... bear with, I'll make an attempt.

**Comment by schlessera** [comment]
You don't need to test object caching. Just test to make sure you don't leave empty site_admin options behind.

**Comment by schlessera** [comment]
Thanks for the pull-request, @javorszky !
